

module Data.Gerber.Abs where

-- Haskell module generated by the BNF converter




data Exp = EAdd Exp Exp | EMul Exp Exp | EInt Integer
  deriving (Eq, Ord, Show, Read)

data Coord = ECoord Exp
  deriving (Eq, Ord, Show, Read)

