

module Data.Gerber.GerberAST.Abs where

-- Haskell module generated by the BNF converter




newtype Generic = Generic String deriving (Eq, Ord, Show, Read)
newtype UIdent = UIdent String deriving (Eq, Ord, Show, Read)
newtype LIdent = LIdent String deriving (Eq, Ord, Show, Read)
data Commands = Program [Command]
  deriving (Eq, Ord, Show, Read)

data Command
    = SingleStandardCommand Generic
    | SingleExtendedCommand Generic
    | MultiExtendedCommands [ExtendedCommandInside]
  deriving (Eq, Ord, Show, Read)

data ExtendedCommandInside = Troll Generic
  deriving (Eq, Ord, Show, Read)

