-- automatically generated by BNF Converter
module Main where


import qualified Data.Gerber.GerberAST.Test as T
import Data.Gerber.GerberAST.Par

--main = T.main
main = do
  a <- readFile "example/scale.gbr"
  T.run 5 pCommands a
  return ()



